# Generated by Django 6.0.3 on 2026-03-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='RefConsumerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип потребителя')),
                ('usage_character', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_data', models.CharField(blank=True, max_length=255, null=True)),
                ('label_on_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_type', models.CharField(blank=True, choices=[('Однофазный', 'Однофазный'), ('Трёхфазный', 'Трёхфазный')], max_length=20, null=True)),
                ('phase_number', models.IntegerField(blank=True, null=True)),
                ('calc_method', models.CharField(blank=True, choices=[('Типовые', 'Типовые'), ('Индивидуальные', 'Индивидуальные')], max_length=20, null=True)),
                ('yearly_consumption_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_active_power_kw', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cos_phi', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Справочник: Типовой потребитель',
                'verbose_name_plural': 'Справочник: Типовые потребители',
                'db_table': 'Ref_Consumer_Types',
            },
        ),
        migrations.CreateModel(
            name='RefLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка ЛЭП')),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('insulation', models.CharField(blank=True, max_length=50, null=True)),
                ('cores_count', models.IntegerField(blank=True, null=True)),
                ('cross_section', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r_phase_ohm_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('r_null_ohm_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('r_add_ohm_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('label_on_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_type', models.CharField(blank=True, choices=[('Однофазная', 'Однофазная'), ('Трёхфазная', 'Трёхфазная')], max_length=20, null=True)),
                ('phase_number', models.IntegerField(blank=True, null=True)),
                ('r_1phase_ohm_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_tap_to_single_pole', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Справочник: Линия',
                'verbose_name_plural': 'Справочник: Линии',
                'db_table': 'Ref_Lines',
            },
        ),
        migrations.CreateModel(
            name='RefTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип трансформатора')),
                ('nominal_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('losses_no_load', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('losses_short_circuit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('voltage_hv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voltage_lv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voltage_short_circuit_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pbv_stages_count', models.IntegerField(blank=True, null=True)),
                ('pbv_step_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('label_on_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('pbv_stage_selected', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Справочник: Трансформатор',
                'verbose_name_plural': 'Справочник: Трансформаторы',
                'db_table': 'Ref_Transformers',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сценария')),
                ('season', models.CharField(choices=[('Зима', 'Зима'), ('Лето', 'Лето'), ('Оба', 'Оба')], default='Зима', max_length=10, verbose_name='Сезонность')),
                ('load_config', models.JSONField(blank=True, null=True, verbose_name='Настройки нагрузок (JSON)')),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'db_table': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('entity_id', models.IntegerField(verbose_name='ID объекта')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='designer.appuser')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'Audit_Logs',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя папки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='designer.folder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='designer.organization')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'db_table': 'Folders',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='designer.organization'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='designer.role'),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('В очереди', 'В очереди'), ('Расчет', 'Расчет'), ('Завершен', 'Завершен'), ('Ошибка', 'Ошибка')], default='В очереди', max_length=20, verbose_name='Статус')),
                ('results_data', models.JSONField(blank=True, null=True, verbose_name='Результаты (JSON)')),
                ('report_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к отчету')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='designer.appuser')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='designer.scenario')),
            ],
            options={
                'verbose_name': 'Расчет (Запуск)',
                'verbose_name_plural': 'Расчеты',
                'db_table': 'Runs',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название схемы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to='designer.appuser')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='designer.folder')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
                'db_table': 'Schemes',
            },
        ),
        migrations.CreateModel(
            name='SchemeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Версия (Метка)')),
                ('topology_data', models.JSONField(verbose_name='Топология (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revisions', to='designer.appuser')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='designer.scheme')),
            ],
            options={
                'verbose_name': 'Версия схемы',
                'verbose_name_plural': 'Версии схем',
                'db_table': 'Scheme_Revisions',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='designer.schemerevision'),
        ),
    ]
