# Generated by Django 6.0.3 on 2026-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка опоры')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал (ЖБ, Дерево, Металл)')),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота, м')),
                ('label_on_scheme', models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись на схеме')),
            ],
            options={
                'verbose_name': 'Справочник: Опора',
                'verbose_name_plural': 'Справочник: Опоры',
                'db_table': 'Ref_Poles',
            },
        ),
    ]
