# Generated by Django 6.0.3 on 2026-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_refpole'),
    ]

    operations = [
        migrations.AddField(
            model_name='refpole',
            name='branches_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Кол-во ответвлений'),
        ),
    ]
