# Generated by Django 6.0.3 on 2026-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_refpole_branches_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='designer.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='designer.folder', verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='additional_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные данные потребителя'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес потребителя'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='calc_method',
            field=models.CharField(blank=True, choices=[('Типовые', 'Типовые'), ('Индивидуальные', 'Индивидуальные')], max_length=20, null=True, verbose_name='Параметры электропотребления (тип)'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='calculated_active_power_kw',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Расчётная активная мощность, кВт'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='cos_phi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Коэффициент мощности (косинус фи)'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='label_on_scheme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись на схеме'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='phase_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер фазы'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('Однофазный', 'Однофазный'), ('Трёхфазный', 'Трёхфазный')], max_length=20, null=True, verbose_name='Питание потребителя'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='usage_character',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Характер электропотребления'),
        ),
        migrations.AlterField(
            model_name='refconsumertype',
            name='yearly_consumption_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Годовое потребление, кВт*ч'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='cores_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество жил'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='cross_section',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сечение фазного провода, мм^2'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='insulation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал изоляции'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='is_tap_to_single_pole',
            field=models.BooleanField(default=False, verbose_name='Отпайка к одиночной опоре'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='label_on_scheme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись на схеме'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина участка ЛЭП, м'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='line_type',
            field=models.CharField(blank=True, choices=[('Однофазная', 'Однофазная'), ('Трёхфазная', 'Трёхфазная')], max_length=20, null=True, verbose_name='Тип ЛЭП'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал провода'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='phase_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер фазы для ЛЭП'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='r_1phase_ohm_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Сопротивление проводов однофазной ЛЭП, Ом/км'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='r_add_ohm_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Сопротивление доп. провода, Ом/км'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='r_null_ohm_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Сопротивление нулевого провода, Ом/км'),
        ),
        migrations.AlterField(
            model_name='refline',
            name='r_phase_ohm_km',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Сопротивление фазного провода, Ом/км'),
        ),
        migrations.AlterField(
            model_name='refpole',
            name='branches_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Количество ответвлений к потребителям и дополнительным линиям'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='label_on_scheme',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись на схеме'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='losses_no_load',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Потери ХХ, кВт'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='losses_short_circuit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Потери КЗ, кВт'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='nominal_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинальная мощность, кВА'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='pbv_stage_selected',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ступень ПБВ'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='pbv_stages_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ступеней ПБВ'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='pbv_step_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Шаг одной ступени ПБВ'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='voltage_hv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинальное напряжение ВН, кВ'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='voltage_lv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Номинальное напряжение НН, кВ'),
        ),
        migrations.AlterField(
            model_name='reftransformer',
            name='voltage_short_circuit_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение КЗ, %'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to='designer.appuser', verbose_name='Создатель схемы'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='designer.folder', verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='schemerevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revisions', to='designer.appuser', verbose_name='Создатель версии'),
        ),
        migrations.AlterField(
            model_name='schemerevision',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='designer.scheme', verbose_name='Схема'),
        ),
    ]
