# Generated by Django 6.0.3 on 2026-03-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_alter_folder_org_alter_folder_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель схемы'),
        ),
        migrations.AlterField(
            model_name='run',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='schemerevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель версии'),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
