# Generated by Django 6.0.3 on 2026-03-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_remove_auditlog_user_alter_scheme_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reftransformer',
            name='label_on_scheme',
        ),
        migrations.RemoveField(
            model_name='reftransformer',
            name='pbv_stage_selected',
        ),
    ]
