# Generated by Django 6.0.3 on 2026-03-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_remove_reftransformer_label_on_scheme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefPole',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='is_tap_to_single_pole',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='label_on_scheme',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='length_m',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='line_type',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='phase_number',
        ),
        migrations.RemoveField(
            model_name='refline',
            name='r_1phase_ohm_km',
        ),
    ]
