# Generated by Django 6.0.3 on 2026-03-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_delete_refpole_remove_refline_is_tap_to_single_pole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refconsumertype',
            name='label_on_scheme',
        ),
    ]
