# Generated by Django 6.0.3 on 2026-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0009_organization_fax_organization_phone_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'permissions': [('export_auditlog', 'Может выгружать журнал аудита'), ('purge_auditlog', 'Может очищать журнал аудита')], 'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'permissions': [('move_folder', 'Может перемещать папки'), ('manage_folder_access', 'Может управлять доступом к папке')], 'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('manage_organization_members', 'Может управлять сотрудниками организации'), ('view_organization_reports', 'Может просматривать отчёты по организации')], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='refconsumertype',
            options={'permissions': [('import_refconsumertype', 'Может импортировать типовых потребителей'), ('export_refconsumertype', 'Может экспортировать типовых потребителей')], 'verbose_name': 'Справочник: Типовой потребитель', 'verbose_name_plural': 'Справочник: Типовые потребители'},
        ),
        migrations.AlterModelOptions(
            name='refline',
            options={'permissions': [('import_refline', 'Может импортировать линии'), ('export_refline', 'Может экспортировать линии')], 'verbose_name': 'Справочник: Линия', 'verbose_name_plural': 'Справочник: Линии'},
        ),
        migrations.AlterModelOptions(
            name='reftransformer',
            options={'permissions': [('import_reftransformer', 'Может импортировать трансформаторы'), ('export_reftransformer', 'Может экспортировать трансформаторы')], 'verbose_name': 'Справочник: Трансформатор', 'verbose_name_plural': 'Справочник: Трансформаторы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('assign_role', 'Может назначать роли пользователям'), ('revoke_role', 'Может снимать роли с пользователей')], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'permissions': [('execute_run', 'Может запускать расчёт'), ('cancel_run', 'Может отменять расчёт'), ('view_run_results', 'Может просматривать результаты расчёта'), ('export_run_report', 'Может выгружать отчёт по расчёту'), ('rerun_run', 'Может перезапускать расчёт')], 'verbose_name': 'Расчет (Запуск)', 'verbose_name_plural': 'Расчеты'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'permissions': [('save_scenario_template', 'Может сохранять сценарий как шаблон'), ('use_scenario_template', 'Может использовать шаблоны сценариев'), ('duplicate_scenario', 'Может дублировать сценарий')], 'verbose_name': 'Сценарий', 'verbose_name_plural': 'Сценарии'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'permissions': [('publish_scheme', 'Может публиковать схему'), ('export_scheme', 'Может экспортировать схему'), ('share_scheme', 'Может делиться схемой с другими пользователями'), ('clone_scheme', 'Может клонировать схему')], 'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AlterModelOptions(
            name='schemerevision',
            options={'permissions': [('approve_revision', 'Может утверждать версию схемы'), ('revert_revision', 'Может откатывать версию схемы'), ('compare_revisions', 'Может сравнивать версии схемы')], 'verbose_name': 'Версия схемы', 'verbose_name_plural': 'Версии схем'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('change_user_organization', 'Может менять организацию пользователя'), ('reset_user_password', 'Может сбрасывать пароль пользователя'), ('impersonate_user', 'Может входить под другим пользователем')], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
